{-# OPTIONS_GHC -Wno-orphans #-}
  -- ^^ Every single instance generated by this module is orphan by definition
{-# LANGUAGE DataKinds #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE FunctionalDependencies #-}
{-# LANGUAGE KindSignatures #-}
{-# LANGUAGE PolyKinds #-}
{-# LANGUAGE TemplateHaskell #-}

module GameMaker.RiskOfRain.Lens where

import           GameMaker.RiskOfRain.Unpacking
import           GameMaker.RiskOfRain.Unpacking.Unpack

import           Control.Lens



makeFields ''PNG

makeFields ''Pointer
makeFields ''Dictionary
makeFields ''DictionaryS

makeFields ''Form

makeFields ''Gen8

makeFields ''Optn

makeFields ''Extn
makeFields ''ExtnTriplet
makeFields ''ExtnSegment
makeFields ''ExtnOperation

makeFields ''Sond
makeFields ''SondElement

makeFields ''Agrp

makeFields ''Sprt
makeFields ''SprtElement

makeFields ''Bgnd
makeFields ''BgndElement

makeFields ''Path

makeFields ''Scpt
makeFields ''ScptBinding

makeFields ''Shdr

makeFields ''Font
makeFields ''FontElement
makeFields ''FontBit

makeFields ''Tmln

makeFields ''Objt
makeFields ''ObjtElement
makeFields ''ObjtSub
makeFields ''ObjtMeta

makeFields ''Room
makeFields ''RoomElement
makeFields ''RoomBackground
makeFields ''RoomView
makeFields ''RoomObject
makeFields ''RoomTile

makeFields ''Dafl

makeFields ''Tpag
makeFields ''TpagElement

makeFields ''Code
makeFields ''CodeFunction

makeFields ''Vari
makeFields ''VariElement

makeFields ''Func
makeFields ''FuncPosition
makeFields ''FuncArguments

makeFields ''Strg
makeFields ''StrgString

makeFields ''Txtr
makeFields ''TxtrElement

makeFields ''Audo
makeFields ''AudoFile
