version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  build-linux:
    machine:
      image: ubuntu-2204:current
    resource_class: medium
    parameters:
      cabal:
        type: string
      ghc:
        type: string
    steps:
      - checkout

      - run:
          name: Install Cabal and GHC
          command: |
            curl --proto '=https' --tlsv1.2 -sSf https://get-ghcup.haskell.org | BOOTSTRAP_HASKELL_NONINTERACTIVE=1 BOOTSTRAP_HASKELL_MINIMAL=1 sh

            PATH=$HOME/.ghcup/bin:$PATH
            echo 'export PATH=$HOME/.ghcup/bin:$PATH' >> $BASH_ENV

            ghcup install cabal << parameters.cabal >>
            ghcup set cabal << parameters.cabal >>

            ghcup install ghc << parameters.ghc >>
            ghcup set ghc << parameters.ghc >>

      - run:
          name: Update Dependencies
          command: cabal update

      - run:
          name: Build
          command: |
            cabal build --enable-tests



workflows:
  workflow:
    jobs:
      - build-linux:
          name: linux-9.8.1
          cabal: 3.10.1.0
          ghc: 9.8.1
